name : CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Install necessary packages
        run: pip install Selenium pytest requests pytest-html pytest-xdist webdriver-manager

      - name: Run Tests
        run: pytest -v -n auto
  
